winget install Mozilla.Firefox -e
winget install Mozilla.FirefoxDeveloperEdition -e
winget install Mozilla.FirefoxESR -e
winget install Google.Chrome -e
winget install Google.ChromeBeta -e
winget install Microsoft.Edge -e
winget install Microsoft.EdgeBeta -e
winget install Microsoft.EdgeDev -e
winget install BraveSoftware.BraveBrowser -e
winget install Opera.Opera -e
