winget install Mozilla.Firefox -e
winget install Mozilla.Firefox.DeveloperEdition -e
winget install Mozilla.Firefox.ESR -e
winget install Mozilla.Firefox.Beta -e
winget install Google.Chrome -e
winget install Google.Chrome.Beta -e
winget install Google.Chrome.Canary -e
winget install Google.Chrome.Dev -e
winget install Microsoft.Edge -e
winget install Microsoft.Edge.Beta -e
winget install Microsoft.Edge.Canary -e
winget install Microsoft.Edge.Dev -e
winget install Brave.Brave -e
winget install Brave.Brave.Beta -e
winget install Brave.Brave.Dev -e
winget install Opera.Opera -e
