code --install-extension DavidAnson.vscode-markdownlint
code --install-extension eamodio.gitlens
code --install-extension GitHub.copilot
code --install-extension GitHub.copilot-chat
code --install-extension Gruntfuggly.todo-tree
code --install-extension leighlondon.eml
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-vscode.powershell
code --install-extension nickdemayo.vscode-json-editor
code --install-extension RaillyHugo.one-hunter
code --install-extension Tailscale.vscode-tailscale
code --install-extension tlahmann.alex-linter
