code --install-extension DavidAnson.vscode-markdownlint
code --install-extension DotJoshJohnson.xml
code --install-extension humao.rest-client
code --install-extension leighlondon.eml
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azure-devops.azure-pipelines
code --install-extension ms-azuretools.vscode-apimanagement
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-azurestorage
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.azurecli
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.vscode-node-azure-pack
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msazurermtools.azurerm-vscode-tools
code --install-extension nickdemayo.vscode-json-editor
code --install-extension redhat.vscode-yaml
code --install-extension vsciot-vscode.azure-iot-toolkit
code --install-extension zhuangtongfa.material-theme
